# Generated by Django 3.1.6 on 2021-02-19 02:13

from django.db import migrations
from StockSight.Initializer.ConfigReader import config

def migrate_default_symbols(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Symbol = apps.get_model('data', 'Symbol')
    SymbolAlias = apps.get_model('data', 'SymbolAlias')
    
    for sym in config.symbols:
        symbol = Symbol.objects.create(name=sym)
        
        for alias in config.symbols[sym]:
            SymbolAlias.objects.create(symbol=symbol, name=alias)
            # symbol.symbol_aliases.create(symbol=symbol, name=alias)

def migrate_default_symbol_twitter_users(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    TwitterUser = apps.get_model('data', 'TwitterUser')
    for username in config.twitter['feeds']:
        TwitterUser.objects.create(username=username)


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_default_symbols),
        migrations.RunPython(migrate_default_symbol_twitter_users),
    ]




        # symbol = Symbol.objects.create(name=sym)
        
        # for alias in config.symbols[sym]:
        #     symbol.symbol_alias_set.create(symbol=symbol, name=alias)


    #    symbol = Symbol(name=sym)
    #    symbol.save()

    #    symbol.
    #    beatles.members.create(name="George Harrison", through_defaults={'date_joined': date(1960, 8, 1)}) 

# def migrate_default_symbol_aliases(apps, schema_editor):
#     '''
#     We can't import the Post model directly as it may be a newer
#     version than this migration expects. We use the historical version.
#     '''
#     SymbolAlias = apps.get_model('data', 'SymbolAlias')

# for post in Post.objects.all():
#         post.slug = slugify(post.title)
#         post.save()

# class Symbol(models.Model):
#     name = models.CharField(max_length=255)
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)

# class SymbolAlias(models.Model):
#     symbol = models.ForeignKey(Symbol, on_delete=models.CASCADE)
#     name = models.CharField(max_length=255)
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)

# class TwitterUser(models.Model):
#     username = models.CharField(max_length=255)
#     user_id = models.BigIntegerField()
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)