# Generated by Django 3.1.7 on 2021-02-20 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210220_2251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleAuthors',
            new_name='ArticleAuthor',
        ),
    ]
